### ISSUE TITLE
Automatically add service to tunnel data to external database

### ISSUE THREAD

**Issue by anbraten** [anbraten/k8s-external-database-operator#1]
The created service name should be configurable by some setting like `serviceName` in the `database` CRD.  Leaving that settings empty / out should prevent the controller from creating a service. The serive should be deployed to the same namespace the `database` CRD is saved to.

## Service creation
Looks like there are two ways:

1. Service with IP-Address

```yml
kind: Service
apiVersion: v1
metadata:
 name: mongo
Spec:
 type: ClusterIP
 ports:
 - port: 27017
   targetPort: 27017
```

```yml
kind: Endpoints
apiVersion: v1
metadata:
 name: mongo # has to be the same name use by the service
subsets:
 - addresses:
     - ip: 10.240.0.4 # ip of the cluster-external mongo database
   ports:
     - port: 27017
```

2. Service with type `ExternalName`  (DNS hostname)

```yml
kind: Service
apiVersion: v1
metadata:
 name: mongo
spec:
 type: ExternalName
 externalName: db123.my-favourite-provider.tld
```

SOURCE: https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services
